services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_task_app
    ports:
      - "8000:8000"
    volumes:
      # Монтируем код для разработки (hot reload)
      - .:/app
      # Сохраняем только файл базы данных на хосте
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn app.fastapi_main:app --host 0.0.0.0 --port 8000 --reload
